# Generated by Django 4.2.7 on 2023-12-01 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_preference', models.CharField(choices=[('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Japanese', 'Japanese')], max_length=50)),
                ('dietary_restrictions', models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan')], max_length=50, null=True)),
                ('location', models.CharField(choices=[('new-york', 'New York'), ('los-angeles', 'Los Angeles'), ('chicago', 'Chicago')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FoodiPrefrence',
        ),
    ]
