# Generated by Django 4.2.7 on 2023-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodiuser',
            name='prefrence',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
    ]
